/**
 * Writes the "Content and attachments" section into every design brief (design-prompts/0*.md).
 *
 * Claude Design sees only the pasted brief and its attachments, never this repo, so every string it
 * may use has to be inside the brief. This section is generated from app/data and i18n/locales,
 * identical in all briefs, and replaced in place between the markers on every run.
 *
 * Run after any content change, before sending a brief: `pnpm brief:content`
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { ExperienceEntry, Localized, Project } from '../shared/types/content'
import { profile } from '../app/data/profile'
import { experience, volunteering } from '../app/data/experience'
import { education, skills } from '../app/data/education'
import { projects } from '../app/data/projects'
import { links } from '../app/data/links'

const root = fileURLToPath(new URL('../', import.meta.url))
const briefsDir = `${root}design-prompts/`
const START = '<!-- content:start · generated by `pnpm brief:content` from the site data; do not edit by hand -->'
const END = '<!-- content:end -->'

type Strings = Record<string, string | Record<string, string>>
const en = JSON.parse(readFileSync(`${root}i18n/locales/en.json`, 'utf8')) as Record<string, Strings>
const cs = JSON.parse(readFileSync(`${root}i18n/locales/cs.json`, 'utf8')) as Record<string, Strings>

// Facts that belong to the briefs, not to the site data.
const projectNotes: Record<string, string[]> = {
  nambi: [
    'The app is private; nambi.cz is its public landing page.',
    'Brand colours (from Nambi\'s own design system): royal blue #4361EE, cerise #EB49C8, persimmon #F87153, deep navy #1A1B51.',
  ],
}

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const month = (iso: string) => iso === 'present'
  ? 'present'
  : `${months[Number(iso.slice(5, 7)) - 1]} ${iso.slice(0, 4)}`
const bare = (url: string) => decodeURI(url).replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '')
const statusLabel = (status: Project['status']) => (en.work!.status as Record<string, string>)[status]
const t = (value: Localized) => value.en

function projectBlock(project: Project) {
  const linkParts = [
    project.links.live && `Live: ${bare(project.links.live)}`,
    project.links.source && `Source: ${bare(project.links.source)}`,
  ].filter(Boolean)
  const lines = [
    `#### ${project.name}`,
    `- ${project.year} · ${statusLabel(project.status)} · ${linkParts.length ? linkParts.join(' · ') : 'no links'}`,
    `- Tagline: ${t(project.tagline)}`,
    `- Summary: ${t(project.summary)}`,
    `- Role: ${t(project.role)}`,
    `- Stack: ${project.stack.join(' · ')}`,
  ]
  if (project.detail) {
    lines.push(`- Problem: ${t(project.detail.problem)}`)
    lines.push('- Decisions:')
    project.detail.decisions.forEach((decision, index) => lines.push(`  ${index + 1}. ${t(decision)}`))
    lines.push(`- Outcome: ${t(project.detail.outcome)}`)
  }
  else {
    lines.push('- No Problem / Decisions / Outcome copy yet.')
  }
  for (const note of projectNotes[project.slug] ?? []) lines.push(`- ${note}`)
  return lines.join('\n')
}

function jobBlock(entry: ExperienceEntry) {
  const lines = [
    `#### ${entry.company}`,
    `- ${entry.from ? `${month(entry.from)} – ` : ''}${month(entry.to)} · ${t(entry.role)}${entry.location ? ` · ${entry.location}` : ''}`,
  ]
  if (entry.summary) lines.push(`- Summary: ${t(entry.summary)}`)
  if (entry.highlights?.length) {
    lines.push('- Highlights:')
    entry.highlights.forEach((highlight, index) => lines.push(`  ${index + 1}. ${t(highlight)}`))
  }
  if (entry.stack?.length) lines.push(`- Stack: ${entry.stack.join(' · ')}`)
  return lines.join('\n')
}

const groupNames: Record<string, string> = {
  nav: 'Navigation',
  work: 'Work',
  experience: 'Experience',
  contact: 'Contact',
  cv: 'CV page',
  settings: 'Settings',
  footer: 'Footer',
}

function uiStrings(locale: Record<string, Strings>) {
  return Object.entries(groupNames)
    .filter(([key]) => locale[key])
    .map(([key, label]) => {
      const values = Object.values(locale[key]!).map(value =>
        typeof value === 'string' ? value : Object.values(value).join(' / '))
      return `- ${label}: ${values.join(' · ')}`
    })
    .join('\n')
}

const featured = projects.filter(project => project.featured)
const more = projects.filter(project => !project.featured)
const degree = education[0]!
const leader = volunteering[0]!

const block = `${START}

## Content and attachments

This section is the only source of facts about Martin and his work: projects, jobs, dates, numbers and quotes. Use every string exactly as written. Anything not listed here does not exist yet: leave it out, never invent it, and never draw lorem ipsum, a placeholder or a TODO box. Interface labels that the brief itself introduces are allowed; every other label comes from the interface strings below. Field names used earlier in the brief (tagline, summary, role, highlights, detail, Problem / Decisions / Outcome) refer to the labels in this section.

### Attachments

- \`portrait-placeholder.jpg\`: Martin's portrait, a stand-in until the real photo arrives. Landscape 3:2 on a dark backdrop; crop it as the brief says.
- \`ref-1-rachelchen-identity-line.jpg\` and \`ref-2-sandwich-hero.jpg\`: Martin's mood references for the hero. The first is a large serif identity sentence with one italic twist word beside an experience table; the second is a big name above a fanned stack of work images above a big role line. Inspiration only: where they differ from this brief, the brief wins. Never copy their text or images.
- \`shot-taboriste.jpg\`: taboriste.fenixb.cz, the Tábořiště Kondor site with its 3D campsite hero.
- \`shot-skautsim.jpg\`: skautsim.fenixb.cz, the SkautSim lobby inside the 3D camp.
- \`shot-becky.jpg\`: beckykaylivingston.cz, the home page of Becky Kay Livingstonová's site.
- \`shot-nambi-landing.jpg\`: nambi.cz, the public Nambi landing page. A brand reference only (colours, logo, type): Nambi's app is private, so its posters show a UI abstraction in Nambi's brand colours, never this page.
- The three site screenshots go inside the poster device frames, cropped as the brief describes. Nuxt Study, Účetnictví Blansko, Skautské hlasování and RoboPilot have no screenshot: where the brief gives one of them a poster, draw a two-tone UI abstraction labelled with the project name.

### Profile

- Name: ${profile.name}
- Headline: ${t(profile.headline)}
- Intro: ${t(profile.intro)}
- Location: ${t(profile.location)}
- E-mail: ${profile.email}
- Links: ${links.map(link => `${link.label} ${bare(link.to)}`).join(' · ')} · Site martinnavratil.dev
- CV files: /martin-navratil-cv.pdf (English), /martin-navratil-cv-cs.pdf (Czech); the CV as a web page lives at /cv.

### Featured projects, in this order

${featured.map(projectBlock).join('\n\n')}

### More projects, in this order

${more.map(projectBlock).join('\n\n')}

### Experience, newest first

${experience.map(jobBlock).join('\n\n')}

### Education

- ${degree.school}${degree.location ? `, ${degree.location}` : ''} · ${t(degree.degree)} · ${t(degree.field)}
${degree.from || degree.to ? `- ${[degree.from, degree.to].filter(Boolean).map(value => month(value!)).join(' – ')}` : '- Years not confirmed yet: show no dates.'}
${degree.note ? `- Note: ${t(degree.note)}` : ''}

### Leadership

- ${leader.company}${leader.location ? `, ${leader.location}` : ''} · ${t(leader.role)}
${leader.from ? `- Since ${month(leader.from)}` : '- Start year not confirmed yet: show no dates.'}
${leader.summary ? `- Summary: ${t(leader.summary)}` : ''}

### Skills

${skills.map(group => `- ${t(group.label)}: ${group.items.join(' · ')}`).join('\n')}

### Interface strings (English)

${uiStrings(en)}

### Czech strings for the fit checks (Czech runs about 20 % longer)

- Headline: ${profile.headline.cs}
- Intro: ${profile.intro.cs}
- Location: ${profile.location.cs}
${uiStrings(cs)}

${END}`

let written = 0
for (const file of readdirSync(briefsDir).filter(name => /^\d{2}-.*\.md$/.test(name)).sort()) {
  const path = briefsDir + file
  let text = readFileSync(path, 'utf8')
  const start = text.indexOf('<!-- content:start')
  const end = text.indexOf(END)
  if (start !== -1 && end !== -1) {
    text = text.slice(0, start) + block + text.slice(end + END.length)
  }
  else {
    // A hand-written content section from an earlier revision is replaced, not duplicated.
    const legacy = text.search(/^## CONTENT\b/m)
    if (legacy !== -1) text = text.slice(0, legacy).trimEnd()
    text = `${text.trimEnd()}\n\n---\n\n${block}\n`
  }
  writeFileSync(path, text)
  written++
  console.log(`${file}: content section written`)
}
if (!written) throw new Error(`No briefs found in ${briefsDir}`)
