/**
 * Writes the "Content and images" section into every design brief (design-prompts/0*.md).
 *
 * Claude Design sees only the pasted brief, never this repo, so every string it may use has to be
 * inside the brief. No images are sent: the briefs ask for labelled placeholders, real images come in code. This section is generated from app/data and i18n/locales,
 * identical in all briefs, and replaced in place between the markers on every run.
 *
 * Run after any content change, before sending a brief: `pnpm brief:content`
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { ExperienceEntry, Localized, Project } from '../shared/types/content'
import { profile } from '../app/data/profile'
import { experience, volunteering } from '../app/data/experience'
import { education, skills } from '../app/data/education'
import { projects } from '../app/data/projects'
import { links } from '../app/data/links'

const root = fileURLToPath(new URL('../', import.meta.url))
const briefsDir = `${root}design-prompts/`
const START = '<!-- content:start · generated by `pnpm brief:content` from the site data; do not edit by hand -->'
const END = '<!-- content:end -->'

type Strings = Record<string, string | Record<string, string>>
const en = JSON.parse(readFileSync(`${root}i18n/locales/en.json`, 'utf8')) as Record<string, Strings>
const cs = JSON.parse(readFileSync(`${root}i18n/locales/cs.json`, 'utf8')) as Record<string, Strings>

// Facts that belong to the briefs, not to the site data.
const projectNotes: Record<string, string[]> = {
  nambi: [
    'The app is private; nambi.cz is its public landing page.',
    'Brand colours (from Nambi\'s own design system): royal blue #4361EE, cerise #EB49C8, persimmon #F87153, deep navy #1A1B51.',
  ],
}

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const month = (iso: string) => iso === 'present'
  ? 'present'
  : `${months[Number(iso.slice(5, 7)) - 1]} ${iso.slice(0, 4)}`
const bare = (url: string) => decodeURI(url).replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '')
const statusLabel = (status: Project['status']) => (en.work!.status as Record<string, string>)[status]
const t = (value: Localized) => value.en

function projectBlock(project: Project) {
  const linkParts = [
    project.links.live && `Live: ${bare(project.links.live)}`,
    project.links.source && `Source: ${bare(project.links.source)}`,
  ].filter(Boolean)
  const lines = [
    `#### ${project.name}`,
    `- ${project.year} · ${statusLabel(project.status)} · ${linkParts.length ? linkParts.join(' · ') : 'no links'}`,
    `- Tagline: ${t(project.tagline)}`,
    `- Summary: ${t(project.summary)}`,
    `- Role: ${t(project.role)}`,
    `- Stack: ${project.stack.join(' · ')}`,
  ]
  if (project.detail) {
    lines.push(`- Problem: ${t(project.detail.problem)}`)
    lines.push('- Decisions:')
    project.detail.decisions.forEach((decision, index) => lines.push(`  ${index + 1}. ${t(decision)}`))
    lines.push(`- Outcome: ${t(project.detail.outcome)}`)
  }
  else {
    lines.push('- No Problem / Decisions / Outcome copy yet.')
  }
  for (const note of projectNotes[project.slug] ?? []) lines.push(`- ${note}`)
  return lines.join('\n')
}

function jobBlock(entry: ExperienceEntry) {
  const lines = [
    `#### ${entry.company}`,
    `- ${entry.from ? `${month(entry.from)} – ` : ''}${month(entry.to)} · ${t(entry.role)}${entry.location ? ` · ${entry.location}` : ''}`,
  ]
  if (entry.summary) lines.push(`- Summary: ${t(entry.summary)}`)
  if (entry.highlights?.length) {
    lines.push('- Highlights:')
    entry.highlights.forEach((highlight, index) => lines.push(`  ${index + 1}. ${t(highlight)}`))
  }
  if (entry.stack?.length) lines.push(`- Stack: ${entry.stack.join(' · ')}`)
  return lines.join('\n')
}

const groupNames: Record<string, string> = {
  nav: 'Navigation',
  work: 'Work',
  experience: 'Experience',
  contact: 'Contact',
  cv: 'CV page',
  settings: 'Settings',
  footer: 'Footer',
}

function uiStrings(locale: Record<string, Strings>) {
  return Object.entries(groupNames)
    .filter(([key]) => locale[key])
    .map(([key, label]) => {
      const values = Object.values(locale[key]!).map(value =>
        typeof value === 'string' ? value : Object.values(value).join(' / '))
      return `- ${label}: ${values.join(' · ')}`
    })
    .join('\n')
}

const featured = projects.filter(project => project.featured)
const more = projects.filter(project => !project.featured)
const degree = education[0]!
const leader = volunteering[0]!

const block = `${START}

## Content and images

This section is the only source of facts about Martin and his work: projects, jobs, dates, numbers and quotes. Use every string exactly as written. Anything not listed here does not exist yet: leave it out, never invent it, and never draw lorem ipsum or a TODO box. Interface labels that the brief itself introduces are allowed; every other label comes from the interface strings below. Field names used earlier in the brief (tagline, summary, role, highlights, detail, Problem / Decisions / Outcome) refer to the labels in this section.

### Images

No images are attached: this design is a layout and motion study for Martin, and the real images are added in code. Wherever the brief mentions the portrait, a screenshot, a device screen or a photo, draw an empty frame at its exact size, aspect ratio, radius and position, filled with a flat neutral tone from the palette and a small mono label naming what will go there, for example "Portrait" or "Screenshot · taboriste.fenixb.cz". Everything else on a poster is designed in full: colour field, grain, monogram, device frame and caption. Only the screen inside the device stays empty. Never generate, search for or invent photos, screenshots, logos or stock imagery.

For context, the hero direction comes from two references Martin liked: a large serif identity sentence with one italic twist word beside an experience table at a glance, and a big name above a fanned stack of work above a big role line. Where they differ from this brief, the brief wins.

### Profile

- Name: ${profile.name}
- Headline: ${t(profile.headline)}
- Intro: ${t(profile.intro)}
- Location: ${t(profile.location)}
- E-mail: ${profile.email}
- Links: ${links.map(link => `${link.label} ${bare(link.to)}`).join(' · ')} · Site martinnavratil.dev
- CV files: /martin-navratil-cv.pdf (English), /martin-navratil-cv-cs.pdf (Czech); the CV as a web page lives at /cv.

### Featured projects, in this order

${featured.map(projectBlock).join('\n\n')}

### More projects, in this order

${more.map(projectBlock).join('\n\n')}

### Experience, newest first

${experience.map(jobBlock).join('\n\n')}

### Education

- ${degree.school}${degree.location ? `, ${degree.location}` : ''} · ${t(degree.degree)} · ${t(degree.field)}
${degree.from || degree.to ? `- ${[degree.from, degree.to].filter(Boolean).map(value => month(value!)).join(' – ')}` : '- Years not confirmed yet: show no dates.'}
${degree.note ? `- Note: ${t(degree.note)}` : ''}

### Leadership

- ${leader.company}${leader.location ? `, ${leader.location}` : ''} · ${t(leader.role)}
${leader.from ? `- Since ${month(leader.from)}` : '- Start year not confirmed yet: show no dates.'}
${leader.summary ? `- Summary: ${t(leader.summary)}` : ''}

### Skills

${skills.map(group => `- ${t(group.label)}: ${group.items.join(' · ')}`).join('\n')}

### Interface strings (English)

${uiStrings(en)}

### Czech strings for the fit checks (Czech runs about 20 % longer)

- Headline: ${profile.headline.cs}
- Intro: ${profile.intro.cs}
- Location: ${profile.location.cs}
${uiStrings(cs)}

${END}`

let written = 0
for (const file of readdirSync(briefsDir).filter(name => /^\d{2}-.*\.md$/.test(name)).sort()) {
  const path = briefsDir + file
  let text = readFileSync(path, 'utf8')
  const start = text.indexOf('<!-- content:start')
  const end = text.indexOf(END)
  if (start !== -1 && end !== -1) {
    text = text.slice(0, start) + block + text.slice(end + END.length)
  }
  else {
    // A hand-written content section from an earlier revision is replaced, not duplicated.
    const legacy = text.search(/^## CONTENT\b/m)
    if (legacy !== -1) text = text.slice(0, legacy).trimEnd()
    text = `${text.trimEnd()}\n\n---\n\n${block}\n`
  }
  writeFileSync(path, text)
  written++
  console.log(`${file}: content section written`)
}
if (!written) throw new Error(`No briefs found in ${briefsDir}`)
